name: build cronjob image

on:
  workflow_dispatch:

env:
  REGION_ID: cn-shanghai
  REGISTRY: registry.cn-shanghai.aliyuncs.com
  NAMESPACE: netilion-china
  IMAGE: test-cronjob
  TAG: ${{ github.sha }}
  ACK_CLUSTER_ID: ce1d89e1ffb644a42ad94a226e5e8aa52
  ACK_DEPLOYMENT_NAME: hub
  DOCKERFILE_NAME: Dockerfile.test_cronjob

jobs:
  build:
    runs-on: ubuntu-latest
    environment: aliyun

    - name: Checkout
      uses: actions/checkout@v2

    # 1.1 Login to ACR
    - name: Login to ACR with the AccessKey pair
      uses: aliyun/acr-login@v1
      with:
        region-id: "${{ env.REGION_ID }}"
        access-key-id: "${{ secrets.ALIYUN_ACCESS_KEY_ID }}"
        access-key-secret: "${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}"

    # 1.2 Buid and push image to ACR
    - name: Build and push image to ACR
      run: |
        docker build -f $DOCKERFILE_NAME --tag "$REGISTRY/$NAMESPACE/$IMAGE:$TAG"  .
        docker push "$REGISTRY/$NAMESPACE/$IMAGE:$TAG"